name: Latest blog post workflow
on:
  schedule:
    # Runs at the end of every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.analyticsvidhya.com/blog/author/kaustubh1828/feed/, https://medium.com/feed/@kaustubhgupta1828, https://www.kaustubhgupta.xyz/blog-feed.xml, https://analyticsindiamag.com/author/kaustubhgupta1828gmail-com/feed/"
          max_post_count: 10
          template: "-$date: [$title]($url):$description $newline"
          gh_token: ${{ secrets.TOKEN }}
          description_max_length: 40
          commit_message: Updated latest blogs
          committer_username: kaustubhgupta
          committer_email: ${{ secrets.EMAIL }}
